### ISSUE TITLE
Can not access the "https://blog.mindorks.com/"

### ISSUE THREAD

**Issue by insomniatt** [MindorksOpenSource/android-dagger2-example#2]
I can access "https://mindorks.com" but I cant access the blog.

**Comment by janishar** [comment]
@insomniatt 
https://blog.mindorks.com/
It is hosted on https://medium.com/ server.
Can you access the Medium website. I think your IP has blocked this. 
Try using some proxy server.

**Comment by insomniatt** [comment]
@janishar 
Hi, I can access now using proxy server.
