### ISSUE TITLE
DaggerActivityComponent missing

### ISSUE THREAD

**Issue by developeromI89** [MindorksOpenSource/android-dagger2-example#4]
DaggerActivityComponent this class is missing in com.mindorks.example.android_dagger2_example.di.component package but still you used in 
com.mindorks.example.android_dagger2_example.MainActivity  class.
How?

**Comment by amitshekhariitbhu** [comment]
Refer https://github.com/MindorksOpenSource/android-mvp-architecture/issues/1

Thank you
Amit Shekhar

**Comment by developeromI89** [comment]
Ok got.
Thank You.
