### ISSUE TITLE
DaggerActivityComponent file not found

### ISSUE THREAD

**Issue by vijayideas** [MindorksOpenSource/android-dagger2-example#8]
The file not in the package- `com.mindorks.example.android_dagger2_example.di.component.DaggerActivityComponent;`

```
public ActivityComponent getActivityComponent() {
        if (activityComponent == null) {
            activityComponent = **DaggerActivityComponent**.builder()
                    .activityModule(new ActivityModule(this))
                    .applicationComponent(DemoApplication.get(this).getComponent())
                    .build();
        }
        return activityComponent;
}
```

**Comment by EddyMM** [comment]
Build the project first then the `ActivityComponent` will be implemented by Dagger2 (creating a `DaggerActivityComponent` class which you can then import).


Dagger2 formulates the dependency graph at build time so a static analyzer would mark the `DaggerActivityComponent` as not found.
